version: "3.7"
services:
  mongo_db:
      image: mongo
      container_name: "mongo_db"
      ports:
        - "27017:27017"
      volumes:
        - mongodb_data:/data/db
      networks:
        - custom

volumes:
  mongodb_data:
    driver: local

networks:
  custom:
    driver: bridge
